# Generated by Django 6.0.1 on 2026-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_order_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
